providers = ["python"]

[phases.setup]
nixPkgs = ["gdbm"]

[phases.install]
# Explicitly use python3.11 for venv creation
cmds = [
  "python3.11 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[python]
version = "3.11"
