# nixpacks.toml - Attempt 2

# Explicitly tell Nixpacks to ONLY use the Python provider,
# overriding any auto-detected ones.
providers = ["python"] # No "..."

[phases.setup]
# Install Python 3.11 and GDBM from Nixpkgs.
# pkgs.python311 provides the python3.11 executable.
nixPkgs = ["pkgs.gdbm", "pkgs.python311"]

# We are not using [phases.install.cmds] for now, to keep it simple.
# The [python].version setting should be the primary way to control this.

[python]
# Tell the Nixpacks Python provider which version to use for all its operations.
# Nixpacks should internally use the correct executable for this version,
# e.g., python3.11 -m venv ...
version = "3.11"
