# nixpacks.toml

[phases.setup]
# This tells Nixpacks to install the 'gdbm' package from the Nixpkgs collection
# before building your Python environment.
# 'pkgs' is a common way to refer to the Nix packages collection.
# The exact package name might vary slightly, but 'gdbm' is very common.
# Another possibility if just 'gdbm' doesn't work could be related to python-specific bindings,
# but typically installing the main 'gdbm' library is enough for Python's built-in dbm module to find it.
nixPkgs = ["pkgs.gdbm"]

# If you need a specific Python version (though Nixpacks usually detects it from requirements.txt or runtime files)
# you can also specify it here, for example:
# [override]
# pythonVersion = "3.11" 
# But usually, just adding the nixPkgs for gdbm is what's needed for this specific error.
