services:
  - type: web
    name: flasktest # Or keep your Render service name
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt" # <-- Uncommented
    startCommand: "gunicorn Day_77_slim_down:app" # <-- Uncommented
